### ISSUE TITLE
Не надо использовать публичные поля

### ISSUE THREAD

**Issue by zaverden** [Rimasko/ikit-mita-hw2#3]
Публичные поля - это нарушение инкапсуляции. Плюс, в задании говорилось, что нужно сделать свойства (property)

```
хотел перечислить их, но у тебя почти все поля -> все надо переделать на свойства
```

**Comment by Rimasko** [comment]
Хорошо, все исправлю

27 мая 2017 г. 23:28 пользователь "Denis Zavershinskiy" <
notifications@github.com> написал:
